services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres_db:5432
      - PORT=8000
    depends_on:
      - postgres_db
    
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
